### Test GET tous les profils
GET http://localhost:3000/profiles

### Test création profil
POST http://localhost:3000/profiles
Content-Type: application/json

{
    "nickname": "test2",
    "email": "test@test2.com",
    "password": "password123",
    "description": "Test profile"
}

### Test mise à jour profil
PUT http://localhost:3000/profiles/1
Content-Type: application/json

{
    "nickname": "test_modifie",
    "email": "test_modifie@test.com",
    "description": "Description modifiée"
}